import type { Metadata } from 'next'
import './globals.css'

import { font } from '@/settings/fonts'
import { cn } from '@/utils/class-names'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className={cn(font.variable, 'font-sans')}>
            <body>{children}</body>
        </html>
    )
}
