import type { Metadata } from 'next'
import './globals.css'

import { montserratFont, kulimParkFont } from '@/settings/fonts'
import { cn } from '@/utils/class-names'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html
            lang="en"
            className={cn(
                montserratFont.variable,
                kulimParkFont.variable,
                'font-sans'
            )}
        >
            <body className="bg-tertiary text-secondary">{children}</body>
        </html>
    )
}
